### ISSUE TITLE
TargetFramework netstandard2.0

### ISSUE THREAD

**Issue by steffbeckers** [KnowledgeForwardSolutions/CheckDigits.Net#30]
I would like to use CheckDigits.Net/GeneralAlgorithms/Modulus10_13Algorithm.cs in my netstandard2.0 project. Has the CheckDigits.Net package a hard dependency on net8.0 or could you add netstandard2.0 to the dependencies?

**Comment by KnowledgeForwardSolutions** [comment]
Thank you for your interest. Let me check into that tomorrow. I wouldn't try creating a netstandard2.0 version of the 2.1 release because I tweaked a couple algorithms for best performance in net8.0. However it may be possible to do something using the 1.x release code.

**Comment by KnowledgeForwardSolutions** [comment]
Interesting. I tried dropping the target framework back to .net5.0 just to see what would happen. I expected that my use of range operators might be an issue, but I found that global usings and file scoped namespaces that the code uses are C# 10 and later. 

To be honest, I lucked out and managed to sidestep the whole .netstandard discussion, and moved directly from .Net 4.8 to .Net Core 3.1 and since then mostly did new development where we were at most one version behind the latest .net version so I'm not entirely sure what constitutes a .netstandard library. (In fact my current dev machine only has .Net Core 3.1 and .Net 5.0 and later frameworks installed.)

Given that you only need the Modulus10_13 algorithm, it might be easier to lift the code for that algorithm directly into your project. That's not a problem license-wise as it grants free use to include all or a portion of the code in your own project. I'd be happy to help you with that if you'd like.

One other question, if you don't mind... Could you tell me how you found about CheckDigits.Net? That would possibly help me in my efforts to get more visibility to the package. Thanks!

**Comment by steffbeckers** [comment]
I'll also take a look at it myself. We found out about your package based on a Google search: "nuget ean13 check digit". Medium article [https://medium.com/@michael.harges/implementing-the-upc-ean-check-digit-algorithm-in-c-e99c26a540c8](https://medium.com/@michael.harges/implementing-the-upc-ean-check-digit-algorithm-in-c-e99c26a540c8) is the first search result.

**Comment by steffbeckers** [comment]
I've created [a PR](https://github.com/KnowledgeForwardSolutions/CheckDigits.Net/pull/31) with the changes I made to get it to work. I packed the source as a local nuget package to test with and was able to reference and use it in a netstandard2.0 project. Feel free to make changes or add comments as needed.

**Comment by KnowledgeForwardSolutions** [comment]
Wow. Let me take a look but that's both unexpected and very cool. How should I credit you in the release notes? As Steff Beckers?

**Comment by KnowledgeForwardSolutions** [comment]
I approved your PR and merged the changes. I'll publish the V2.2.0 version tomorrow afternoon (Pacific time in the US).

Thanks for your work!

**Comment by steffbeckers** [comment]
Thank you! I'll test the new version when it's published.

**Comment by KnowledgeForwardSolutions** [comment]
The package is published and available now. Let me know how your tests go and I'll close out the issue if everything works for you.

Again, I appreciate your help. This will widen the applicability of the library and that wouldn't have happened without you.

**Comment by steffbeckers** [comment]
Works as expected now, thanks!

![image](https://github.com/KnowledgeForwardSolutions/CheckDigits.Net/assets/7551394/42233b90-2058-4b84-ab5a-111b6874e79e)

**Comment by KnowledgeForwardSolutions** [comment]
Awesome! Glad it's working for you.

One thing to note is that the check for IsNullOrWhiteSpace in your IsValid method is not strictly necessary as those cases are handled in the algorithm as well. A value that is null, String.Empty or that contains any non-digit character will return a value of false.

**Comment by steffbeckers** [comment]
I saw the CheckDigits.Net project also has Nullable enabled, maybe you could also use the "string?" notation on the value parameter of the Validate method? This is also why I currently do the extra check.

![image](https://github.com/KnowledgeForwardSolutions/CheckDigits.Net/assets/7551394/f94850e8-c6bc-44c6-87da-a865f8e4d5fa)
